### ISSUE TITLE
nixpkgs

### ISSUE THREAD

**Issue by mightyiam** [peterldowns/nix-search-cli#4]
Any chance to get this on nixpkgs?

**Comment by peterldowns** [comment]
I'm not sure how one goes about doing that, if you can point me to instructions (or want to do it yourself) I have no objection whatsoever.

**Comment by mightyiam** [comment]
I appreciate your response. Here are [the official docs](https://nixos.org/manual/nixpkgs/stable/#id-1.6).

**Comment by peterldowns** [comment]
Thank you. I'll get around to this at some point. I'll leave this issue open until I've finished. In the meantime, please let me know if you have any other feedback, criticism, or suggestions — and I hope you find the software useful.

**Comment by peterldowns** [comment]
Closing as wontfix — I spent twenty minutes trying to figure out an easy way to reuse this flake in nixpkgs but I didn’t see an easy answer, and it made me hate Nix even more than I do already (surprising, since I already hate Nix a lot.) If anyone else would like to, you’re welcome to go ahead with my blessing.

**Comment by donovanglover** [comment]
Hi, I made a pull request here: https://github.com/NixOS/nixpkgs/pull/266689

Thanks for making nix-search-cli!
